<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="POU11" Id="{72f8079d-9744-4eaf-b09b-d0f4d955c356}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM POU11
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="POU11">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>